---
data_content:
  checkSSL: false
        # Name of application
  applicationId: 9949-fao-frontal
        # Username account for get a token
  username: '%env(GED_USERNAME)%'
        # Password  for get a token
  password: '%env(GED_PASSWORD)%    '
        # URL for get a token
  tokenAuthSsoUrl: '%env(GED_GINA_URL_SSO)%'
        # Timeout for token in seconds
  tokenTimeout: 15
        # Timeout for DataContent in seconds
  timeout: 20
        # Ged client secret
  clientSecret: '%env(GED_CLIENT_SECRET)%'
        # GED client Id
  clientId: '%env(GED_CLIENT_ID)%'
        # URL for GED REST request
  restUrl: '%env(GED_REST_URL)%'
        # Base ID
  baseId: '%env(GED_BASE_ID)%'
        # Audience for token request
  audience: GED.DFCE
        # service for token authentication
#  tokenAuthenticatorClass: ~
...