data_content:
  checkSSL: false
        # Name of application
  applicationId: '%env(GED_APPLICATION_ID)%'
        # Username of gina technical account for get a token
  username: '%env(GED_USERNAME)%'
        # Password of gina technical account for get a token
  password: '%env(GED_PASSWORD)%'
        # URL for get a token from GINA
  tokenAuthSsoUrl: '%env(GED_GINA_URL_SSO)%'
        # Timeout for token in seconds
  tokenTimeout: '%env(GED_TOKEN_TIMEOUT)%'
        # Timeout for datacontent in seconds
  timeout: '%env(GED_TIMEOUT)%'
        # URL for GED REST request
  clientSecret: '%env(GED_CLIENT_SECRET)%'
        # GED client Id
  clientId: '%env(GED_CLIENT_ID)%'
        # URL for GED REST request
  restUrl: '%env(GED_REST_URL)%'
        # Base ID
  baseId: '%env(GED_BASE_ID)%'
        # Audience for token request
  audience: '%env(GED_AUDIENCE)%'
