---
nbgrp_onelogin_saml:
  onelogin_settings:
    default:
      idp:
        entityId: '%env(APP_IDP_ENTITY_ID)%'
        singleSignOnService:
          url: '%env(APP_IDP_SINGLESIGNONSERVICE_URL)%'
          #          binding: '%env(IDP_SINGLESIGNONSERVICE_BINDING)%' -> bug voir https://github.com/nbgrp/onelogin-saml-bundle/issues/36
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
          url: '%env(APP_IDP_SINGLELOGOUTSERVICE_URL)%'
          #          binding: '%env(IDP_SINGLELOGOUTSERVICE_BINDING)%' -> bug voir https://github.com/nbgrp/onelogin-saml-bundle/issues/36
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: '%env(APP_IDP_X509CERT)%'
      sp:
        entityId: '%env(APP_URL)%/saml/metadata'
        assertionConsumerService:
          url: '%env(APP_URL)%/saml/acs'
        singleLogoutService:
          url: '%env(APP_URL)%/saml/logout'
        privateKey: ''
      baseurl: '%env(APP_URL)%/saml'
      strict: true
      debug: true
      security:
        nameIdEncrypted: false
        authnRequestsSigned: false
        logoutRequestSigned: false
        logoutResponseSigned: false
        wantMessagesSigned: false
        wantAssertionsSigned: false
        wantNameIdEncrypted: false
        requestedAuthnContext: true
        signMetadata: false
        wantXMLValidation: true
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
...
