FROM adminer 
COPY ./docker/config/adminer/html /var/www/html
USER	root
COPY ./docker/config/adminer/my-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/my-entrypoint.sh
ENTRYPOINT	[ "my-entrypoint.sh", "docker-php-entrypoint" ]
USER adminer
CMD php -S [::]:8080 -t /var/www/html
