---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'

  App\Tests\Behat\TestMiddleware:
    tags:
      - { name: doctrine.middleware, priority: 5000 }
...
