#!/usr/bin/env sh
vendor/bin/php-cs-fixer check
vendor/bin/twig-cs-fixer lint
bin/console lint:container
bin/console lint:twig --show-deprecations templates
bin/console lint:yaml config src
vendor/bin/phpstan analyse
vendor/bin/rector process --dry-run
npx eslint assets
