name: check quality code
on: push
jobs:
  mycheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: php-cs-fixer
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
        
      - name: install yarn  
        run: npm install --global yarn

      - name: eslint  
        run: npm i -g eslint  

      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer check

      - name: Run twig-cs-fixer
        run: vendor/bin/twig-cs-fixer lint

      - name: Run lint:container
        run: bin/console lint:container

      - name: Run lint:twig
        run: bin/console lint:twig --show-deprecations templates

      - name: Run lint:yaml
        run: bin/console lint:yaml config src

      - name: Run phpstan
        run: vendor/bin/phpstan analyse

      - name: Run rector
        run: vendor/bin/rector process --dry-run

      - name: behat code coverage
        run: cd htdocs
      - run:  yarn encore prod
      - run: cd ..
      - run: vendor/bin/behat --xdebug 
      
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
#        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md        
