name: check quality code
on: push
jobs:
  mycheck:
    permissions:
      pull-requests: write
      contents: write           
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.        
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: php-cs-fixer
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - run: npm install --global yarn    
      - run: yarn install --force
      - run: yarn encore prod    
      - run: npm i -g eslint  

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
 
      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer check

      - name: Run twig-cs-fixer
        run: vendor/bin/twig-cs-fixer lint

      - name: Run lint:container
        run: bin/console lint:container

      - name: Run lint:twig
        run: bin/console lint:twig --show-deprecations templates

      - name: Run lint:yaml
        run: bin/console lint:yaml config src

      - name: Run phpstan
        run: vendor/bin/phpstan analyse

      - name: Run rector
        run: vendor/bin/rector process --dry-run

      - name: behat code coverage
        run: vendor/bin/behat --xdebug 
      
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md        

      - name: archive
        run: git config --local user.name actions-user
      - run:  git config --local user.email "actions@github.com" 
      - run: git add code-coverage-results.md
      - run: git commit -m "chore':' update code coverage results"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

